export const cardDesk = [
    {
        id: 'a1',
        name:'A1',
        img:"img/cards/a1.png",
    },
    {
        id: 'a2',
        name:'A2',
        img:"img/cards/a2.png",
    },
    {
        id: 'a3',
        name:'A3',
        img:"img/cards/a3.png",
    },
    {
        id: 'a4',
        name:'A4',
        img:"img/cards/a4.png",
    },
    {
        id: 'j1',
        name:'J1',
        img:"img/cards/j1.png",
        point: 10,
    },
    {
        id: 'j2',
        name:'J2',
        img:"img/cards/j2.png",
        point: 10,
    },
    {
        id: 'j3',
        name:'J3',
        img:"img/cards/j3.png",
        point: 10,
    },
    {
        id: 'j4',
        name:'J4',
        img:"img/cards/j4.png",
        point: 10,
    },
    {
        id: 'k1',
        name:'K1',
        img:"img/cards/k1.png",
        point: 10,
    },
    {
        id: 'k2',
        name:'K2',
        img:"img/cards/k2.png",
        point: 10,
    },
    {
        id: 'k3',
        name:'K3',
        img:"img/cards/k3.png",
        point: 10,
    },
    {
        id: 'k4',
        name:'K4',
        img:"img/cards/k4.png",
        point: 10,
    },
    {
        id: 'q1',
        name:'Q1',
        img:"img/cards/q1.png",
        point: 10,
    },
    {
        id: 'q2',
        name:'Q2',
        img:"img/cards/q2.png",
        point: 10,
    },
    {
        id: 'q3',
        name:'Q3',
        img:"img/cards/q3.png",
        point: 10,
    },
    {
        id: 'q4',
        name:'Q4',
        img:"img/cards/q4.png",
        point: 10,
    },
    {
        id: '21',
        name:'21',
        img:"img/cards/21.png",
        point: 2,
    },
    {
        id: '22',
        name:'22',
        img:"img/cards/22.png",
        point: 2,
    },
    {
        id: '23',
        name:'23',
        img:"img/cards/23.png",
        point: 2,
    },
    {
        id: '24',
        name:'24',
        img:"img/cards/24.png",
        point: 2,
    },
    {
        id: '31',
        name:'31',
        img:"img/cards/31.png",
        point: 3,
    },
    {
        id: '32',
        name:'32',
        img:"img/cards/32.png",
        point: 3,
    },
    {
        id: '33',
        name:'33',
        img:"img/cards/33.png",
        point: 3,
    },
    {
        id: '34',
        name:'34',
        img:"img/cards/34.png",
        point: 3,
    },
    {
        id: '41',
        name:'41',
        img:"img/cards/41.png",
        point: 4,
    },
    {
        id: '42',
        name:'42',
        img:"img/cards/42.png",
        point: 4,
    },
    {
        id: '43',
        name:'43',
        img:"img/cards/43.png",
        point: 4,
    },
    {
        id: '44',
        name:'44',
        img:"img/cards/44.png",
        point: 4,
    },
    {
        id: '51',
        name:'51',
        img:"img/cards/51.png",
        point: 5,
    },
    {
        id: '52',
        name:'52',
        img:"img/cards/52.png",
        point: 5,
    },
    {
        id: '53',
        name:'53',
        img:"img/cards/53.png",
        point: 5,
    },
    {
        id: '54',
        name:'54',
        img:"img/cards/54.png",
        point: 5,
    },
    {
        id: '61',
        name:'61',
        img:"img/cards/61.png",
        point: 6,
    },
    {
        id: '62',
        name:'62',
        img:"img/cards/62.png",
        point: 6,
    },
    {
        id: '63',
        name:'63',
        img:"img/cards/63.png",
        point: 6,
    },
    {
        id: '64',
        name:'64',
        img:"img/cards/64.png",
        point: 6,
    },
    {
        id: '71',
        name:'71',
        img:"img/cards/71.png",
        point: 7,
    },
    {
        id: '72',
        name:'72',
        img:"img/cards/72.png",
        point: 7,
    },
    {
        id: '73',
        name:'73',
        img:"img/cards/73.png",
        point: 7,
    },
    {
        id: '74',
        name:'74',
        img:"img/cards/74.png",
        point: 7,
    },
    {
        id: '81',
        name:'81',
        img:"img/cards/81.png",
        point: 8,
    },
    {
        id: '82',
        name:'82',
        img:"img/cards/82.png",
        point: 8,
    },
    {
        id: '83',
        name:'83',
        img:"img/cards/83.png",
        point: 8,
    },
    {
        id: '84',
        name:'84',
        img:"img/cards/84.png",
        point: 8,
    },
    {
        id: '91',
        name:'91',
        img:"img/cards/91.png",
        point: 9,
    },
    {
        id: '92',
        name:'92',
        img:"img/cards/92.png",
        point: 9,
    },
    {
        id: '93',
        name:'93',
        img:"img/cards/93.png",
        point: 9,
    },
    {
        id: '94',
        name:'94',
        img:"img/cards/94.png",
        point: 9,
    },
    {
        id: '101',
        name:'101',
        img:"img/cards/101.png",
        point: 10,
    },
    {
        id: '102',
        name:'102',
        img:"img/cards/102.png",
        point: 10,
    },
    {
        id: '103',
        name:'103',
        img:"img/cards/103.png",
        point: 10,
    },
    {
        id: '104',
        name:'104',
        img:"img/cards/104.png",
        point: 10,
    },
]